---
course: data-engineering-zoomcamp
id: 27fa940238
question: Problem with importing the dlt or dlt.sources module
section: Workshop 1 - dlthub
sort_order: 4410
---

Make sure you donâ€™t have a dlt.py file saved in the same directory as your working file.

