---
id: ba210ca8ef
question: I changed location in dbt, but dbt run still gives me an error
section: Module 4: analytics engineering with dbt
course: data-engineering-zoomcamp
sort_order: 2680
---

Remove the dataset from BigQuery which was created by dbt and run dbt run again so that it will recreate the dataset in BigQuery with the correct location

